version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-express-app
    container_name: my-express-container
    restart: always
    ports:
      - 3000:3000
    environment:
      MONGO_URL: mongodb://0.0.0.0:27017/nexus
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
