name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Github Packages registry
        run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        env:
          IMAGE_TAG: my-express-app:latest
          REGISTRY_URL: ghcr.io
        run: |
          docker build -t $IMAGE_TAG .
          docker tag $IMAGE_TAG $REGISTRY_URL/${{ github.repository_owner }}/$IMAGE_TAG
          docker push $REGISTRY_URL/${{ github.repository_owner }}/$IMAGE_TAG

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            docker stop my-express-app || true
            docker rm my-express-app || true
            docker pull ghcr.io/${{ github.repository_owner }}/my-express-app:latest
            docker run -d --name my-express-app -p 8000:8000 ghcr.io/${{ github.repository_owner }}/my-express-app:latest
