name: Deploy to VPS

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: my-express-app
  REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
  REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
  REGISTRY_URL: ${{ secrets.REGISTRY_URL }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker build -t $IMAGE_NAME .

    - name: Push Docker image to registry
      run: |
        docker tag $IMAGE_NAME $REGISTRY_URL/$IMAGE_NAME
        if docker login -u $REGISTRY_USERNAME -p $DOCKERHUB_ACCESS_TOKEN $REGISTRY_URL ; then
          docker push $REGISTRY_URL/$IMAGE_NAME
        else
          echo "Login failed"
          exit 1
        fi

    - name: SSH to VPS and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.VPS_PASSWORD }}
        script: |
          docker-compose down
          docker-compose pull
          docker-compose up -d
